### ISSUE TITLE
YOLO files

### ISSUE THREAD

**Issue by lavrenkov-sketch** [levanquoc/masked-face-recognition#1]
Hello doesn't have files how can I get them?
"yolov3.weights","yolov3.cfg","yolo.names"

**Comment by levanquoc** [comment]
Please contact with me through skype.



------------------------------------------------------------------------------------------------

Le Van Quoc

Danang University of Science and Technology, The University of Danang

Mobile: (+84) (038) 4937977

Skype ID: levanquocbkdn_1

Email: levanquocbkdn@gmail.com


Vào Th 5, 1 thg 10, 2020 vào lúc 12:27 Nikita Lavrenkov <
notifications@github.com> đã viết:

**Comment by dazzcreations** [comment]
Hello, 
I have sent you the mail and contacted via Skype too, please respond :)

**Comment by lavrenkov-sketch** [comment]
He don't send this files

**Comment by dazzcreations** [comment]
> He don't send this files

Yes, I think he forgot about this repository of his.

**Comment by levanquoc** [comment]
Sorry,result research not good,So I can't send it

**Comment by levanquoc** [comment]
.....................................

Quoc would like to stay in touch on LinkedIn.

Quoc Le Van
Research And Development Engineer at ASTI Electronics INDIA Pvt Ltd
Vietnam

View profile https://www.linkedin.com/comm/in/quoc-le-van-2994bb149?trk=eml-guest-invite-pprofile-link-cta&trkEmail=eml-email_m2g_invite_single_01-null-373-null-null-%7E7a8dix%7Ekk2dyu2m%7Ej4-null-neptune%2Fprofile%7Evanity%2Eview&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BBwIBRcclT4%2B29JeqQ2pNvA%3D%3D

Confirm that you know Quoc https://www.linkedin.com/e/v2?e=-7a8dix-kk2dyu2m-j4&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BBwIBRcclT4%2B29JeqQ2pNvA%3D%3D&t=suwj&tracking=eml-guest-invite-cta&ek=email_m2g_invite_single_01&validationToken=l3LW19DC&invitationId=6756869844332875776


.....................................

Unsubscribe: https://www.linkedin.com/e/v2?e=-7a8dix-kk2dyu2m-j4&t=lun&midToken=AQFmrFVhGEd36Q&ek=email_m2g_invite_single_01&li=381&m=unsub&ts=unsub&loid=AQGZYM1OHLkWhgAAAXcU5ZeRmvWnrT8_-1YqdA6KlAa6JuIjGgDNmrRKnE5dMNroQVXf533JAc_DgukOqzEiO--Pzs1zSL4we9v-S0cFB1rircVRmUXOqpmsyV_eCNjKh3e5seS_BR-UALF32wCKDP7_G4ZmIxQqBg&eid=-7a8dix-kk2dyu2m-j4

Help: https://www.linkedin.com/e/v2?e=-7a8dix-kk2dyu2m-j4&lipi=urn%3Ali%3Apage%3Aemail_email_m2g_invite_single_01%3BBwIBRcclT4%2B29JeqQ2pNvA%3D%3D&a=customerServiceUrl&ek=email_m2g_invite_single_01&li=380&m=footer&ts=help&articleId=67


You are receiving Invitation emails. LinkedIn will use your email address to make suggestions to our members in features like People You May Know.

This email was sent to reply@reply.github.com.

© 2021 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2. LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
